import { RouteCardData } from "@/components/route-card";

export const featuredRoutes: RouteCardData[] = [
    {
        id: "tmb",
        region: "France · Italy · Switzerland",
        difficulty: "Challenging",
        tagline: "The Classic Alpine Circuit",
        name: "Tour du Mont Blanc",
        distance: "170 km",
        ascent: "10k↑",
        duration: "11 d",
        months: ["Jul", "Aug", "Sep"],
        imageSrc: "/images/tmb-map.png",
        available: false,
    },
    {
        id: "alta-via-1",
        region: "Italy · Dolomites",
        difficulty: "Challenging",
        tagline: "High Route Through the Dolomites",
        name: "Alta Via 1",
        distance: "120 km",
        ascent: "8k↑",
        duration: "9 d",
        months: ["Jul", "Aug", "Sep"],
        href: "/plan",
        imageSrc: "/images/alta-via-1-map.png",
        available: true,
    },
    {
        id: "gr20",
        region: "France · Corsica",
        difficulty: "Strenuous",
        tagline: "Europe's Toughest Long-Distance Trail",
        name: "GR20",
        distance: "180 km",
        ascent: "13k↑",
        duration: "14 d",
        months: ["Jun", "Jul", "Sep"],
        imageSrc: "/images/gr20-map.png",
        available: false,
    },
];
